import type { Metadata } from "next";
import { Providers } from "./provider";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Navbar from "./navbar";
config.autoAddCss = false
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={pretendard.variable}>
      <body className={pretendard.className}>
        <Providers>
          <header>
            <Navbar />
          </header>
          {children}
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
