import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./components/Provider";
import { config } from '@fortawesome/fontawesome-svg-core'
import Footer from "./components/Footer";
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import localFont from "next/font/local";
import NavbarManager from "./components/NavbarManager";


export const metadata: Metadata = {
  title: "LookBook",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1.0,
};

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="kr" className={pretendard.variable}>
      <body className={pretendard.className}>
        <Providers>
          <header>
            <NavbarManager />
          </header>
          {children}
          <footer>
            <Footer />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
